### ISSUE TITLE
Possible to link in to an adjacent academic edifice

### ISSUE THREAD

**Issue by technicalities** [johnny-morrice/amoebethics#1]
One of the worthy Nobelist economists, Schelling wrote a highly formal agent model in which segregation can just emerge from mild preferences and path dependency. 
http://ncase.me/polygons/

More generally, are we looking for processes to create patterns (1960 Alabama, 1993 Somalia) or just tinkering with assumptions and seeing? An unvisualised Monte Carlo simulator could be cool in the service of the first goal (what parameters result in state `x`?).

**Comment by johnny-morrice** [comment]
Our plan was to simulate the transmission of beliefs?  Not to create patterns, yeah?

Interesting that our simulation is continuous and Schelling's is discrete.

I am interested in playing more first.  We don’t even have activist types.  

Nor do we have much in the way of render technology other than PNG output and shellscripts to munge them into a video.

So at the moment I am happy to continue tinkering with the beliefs system and seeing what emerges from our ideas, rather than attempting to jump onto some preexisting bandwagon.

**Comment by johnny-morrice** [comment]
Maybe you are asking if the simulator could be extended so that nodes can examine each other’s beliefs.  If you did that, creating Schelling nodes would not be difficult.

**Comment by johnny-morrice** [comment]
Actually, yes, we can definitely already do this.  It is totally possible to develop schelling nodes in this system.

**Comment by johnny-morrice** [comment]
Nodes can inspect each other's beliefs, so it should be trivial to create Schelling nodes.

Feel free to raise a new issue with a concrete proposal for the behaviour of these nodes within a continuous space.
